### PR TITLE
[zh-tw] Supervised learning

### PR DESCRIPTION
**Pull request by kevingo**
Finish the `supervised learning` zh-tw translation. Also add the missing part, please ref to this issue : https://github.com/shervinea/cheatsheet-translation/issues/74

### CODE REVIEW

**Comment by shervinea** [comment]
Thanks @kevingo for your hard work! This is great. Now, let's start the review process.

**Comment by kevingo** [comment]
@accelsao Thanks. 看起來不錯，我會修改一下

**Comment by accelsao** [comment]
Review Done !

**Comment by accelsao** [comment]
可阿

**Comment by shervinea** [comment]
Thank you everyone for your hard work!

**Pull request merged**
