### PR TITLE
[tr] Supervised learning and [tr] Deep learning

### PR DESCRIPTION
**Pull request by yavuzKomecoglu**

### CODE REVIEW

**Comment by yavuzKomecoglu** [comment]
How does the review and approval process work?

**Comment by shervinea** [comment]
Hi @yavuzKomecoglu, thanks for helping us with the translation!

The translation and review process are detailed in the [README file](https://github.com/shervinea/cheatsheet-translation/blob/master/README.md). After the translation is done, other native speakers acting as reviewers will go through each sentence and suggest improvements when necessary.

I saw that you are translating two cheatsheets: could you please open a separate pull request for each of them? It will help simplify the review process.

**Comment by yavuzKomecoglu** [comment]
@shervinea, thanks for your return.
I sent two cheatsheets of the translation separately as a new pull request.
[[tr] Unsupervised Learning](https://github.com/shervinea/cheatsheet-translation/pull/112) and [[tr] Deep learning](https://github.com/shervinea/cheatsheet-translation/pull/113)

**Comment by shervinea** [comment]
Awesome, thank you @yavuzKomecoglu! I am closing this PR then.

**Pull request closed without merging**
