### PR TITLE
[zh] Supervised learning

### PR DESCRIPTION
**Pull request by hongnianwang**

### CODE REVIEW

**Comment by hongnianwang** [comment]
done

**Comment by cxue4ur19** [comment]
@shervinea Review. This is very good, I think the document is not only correct but also more importantly natural for native speakers to read.  

A comment: contributors from other topics had chosen different translations for "cheatsheet" and "introduction"; It might be the best to have consistency for the titles.

**Comment by shervinea** [comment]
@cxue4ur19 Thanks for your comment. Please feel free to directly annotate the markdown file for these suggestions.

**Comment by tigerneil** [comment]
@shervinea I prefer "简明指南" for cheatsheet

**Comment by shervinea** [comment]
@tigerneil Thanks for your comment. Can you please directly comment on the code, so that @hongnianwang can modify things accordingly?

**Comment by hongnianwang** [comment]
No problem 👌🏻

Shervine Amidi <notifications@github.com>于2018年10月3日 周三07:56写道：

**Comment by shervinea** [comment]
Thank you everyone! Merging it.

**Comment by hongnianwang** [comment]
sure, thanks for your reminder

**Pull request merged**
