### PR TITLE
[ar] Probabilities and Statistics

### PR DESCRIPTION
**Pull request by moun3imy**
I'm working on translating Probability file to Arabic

### CODE REVIEW

**Comment by shervinea** [comment]
@moun3imy Thanks for helping us out! 

I noticed that a PR about this cheatsheet is already open at #26. I propose that we focus our efforts there to avoid any overlap.

**Comment by moun3imy** [comment]
@shervinea  yeah it's dated to 16 Sep it's been a while now

**Comment by shervinea** [comment]
Let's first wait for a day to see what @slashtea thinks about it. It is important not to discard valuable previous work and their contributors.

**Comment by mhmoodlan** [comment]
Hi @moun3imy, what is the status of this PR?

**Comment by shervinea** [comment]
Closing this PR as the translation continues in #182.

**Pull request closed without merging**
