### PR TITLE
[ko] cs-229-supervised-learning

### PR DESCRIPTION
**Pull request by rickiepark**
WIP :)

### CODE REVIEW

**Comment by shervinea** [comment]
Thank you a lot for your work @rickiepark! One small comment: could you please just keep the supervised learning file in the PR? That way, merging will not cause any conflict.

**Comment by rickiepark** [comment]
Hi @shervinea,
Sorry, I'm lots of thing to do these days.
I don't mind someone continue my work.
Thanks.

**Comment by shervinea** [comment]
Ok that works, thank you for your prompt feedback @rickiepark!

**Comment by kimdanny** [comment]
Seems like no one has taken over his work yet. Can I take an honor to continue @rickiepark 's translation?
What would be the best way that I can continue working on top of his work while keeping his contribution intact?

**Comment by shervinea** [comment]
That would be great, thank you for your help @kimdanny! You could create a new pull request and start from the current progress. We'll have to make sure to not forget to include @rickiepark in the `CONTRIBUTORS` file as well.

**Comment by shervinea** [comment]
Continuation of this work at #214.

**Pull request closed without merging**
