### PR TITLE
[hu] Supervised Learning

### PR DESCRIPTION
**Pull request by balazs-vida**
Done with the Supervised Learning cheat sheet. Still looking for potential native reviewers though...

(@shervinea Sorry, it looks like I just tried to merge not only the Supervised Learning but the Refreshers too in this pull request. Apparently I couldn't exactly figure out the process of submitting pull requests, but I'm doing my best so that the other translations will work out smoothly. Sorry about this!)

### CODE REVIEW

**Comment by shervinea** [comment]
Thanks a lot for your hard work @balazs-vida! 

I think it will work better if we create a branch where the only addition is `cheatsheet-supervised-learning.md`. Let me know if that works!

**Comment by balazs-vida** [comment]
So if I understand it correctly, the source of the problem is that all of the current branches on my end contain all commits and files that have been changed. So basically I have to create a new branch within the repository that contains only `cheatsheet-supervised-learning.md` (or any other translated sheets) and start a pull request using that branch (how can I do this without affecting other sheets?)
If I'm missing something, could you please guide me in the right direction? And sorry for the mess, I really want this to work.

**Comment by shervinea** [comment]
@balazs-vida That's exactly right! Creating a branch dedicated to a cheatsheet and opening a pull request should do the trick.

Thanks again for your time and work!

**Comment by shervinea** [comment]
PR submitted in #132

**Pull request closed without merging**
