### PR TITLE
[pt] Machine learning tips and tricks

### PR DESCRIPTION
**Pull request by leportella**

### CODE REVIEW

**Comment by leportella** [comment]
@gabriel19913 could you take a look at this?

**Comment by shervinea** [comment]
Thank you @leportella, that looks great!

PS: It seems that number 23 is missing

**Comment by gabriel19913** [comment]
Hi @leportella I think @fersantos-dev already began a translation of this file. Could you please take a look? https://github.com/shervinea/cheatsheet-translation/pull/57

**Comment by shervinea** [comment]
Thanks for the info @gabriel19913! Let's all focus our efforts on #57 then.

**Comment by leportella** [comment]
That's weird. When I looked there was no PR on this o.O

**Comment by shervinea** [comment]
@leportella Thanks for the feedback. I think the format of the README wasn't very useful to track ongoing PRs. I've [remodeled it a bit](https://github.com/shervinea/cheatsheet-translation/blob/master/README.md) so that it can hopefully be more helpful in the future.

**Pull request closed without merging**
