### PR TITLE
[zh] Deep learning

### PR DESCRIPTION
**Pull request by tigerneil**
complete all.

### CODE REVIEW

**Comment by shervinea** [comment]
Excellent @tigerneil, thank you for working on this!
Now, let's wait for a reviewer!

**Comment by shervinea** [comment]
Just realized that the translation of the same cheatsheet had also been completed [in this PR](https://github.com/shervinea/cheatsheet-translation/pull/12).

@tigerneil could you please review the translation there, and compare it with what you have translated? I am closing this PR so that we can work at a same place.

**Comment by tigerneil** [comment]
I do consider this version is better than that one. :'( 
I found several improper terms there.

**Comment by shervinea** [comment]
Ok, thanks for taking the time to look at it. Could you please propose all your changes there, so that we can proceed with the review?

**Comment by tigerneil** [comment]
Ok, no problem.

**Pull request closed without merging**
