### PR TITLE
[ko] cs-229-deep-learning

### PR DESCRIPTION
**Pull request by rickiepark**
Working in progress. :)

### CODE REVIEW

**Comment by rickiepark** [comment]
@shervinea I finish translation of deep learning. :)

**Comment by shervinea** [comment]
Awesome work @rickiepark! 

Now, let's wait for a reviewer to come and take a look at the translation.

**Comment by rickiepark** [comment]
👍

**Comment by kimdanny** [comment]
@shervinea I've reviewed his work on cs-229-deep-learning translation, and it was perfect. Couldn't find any line to point out. Actually @rickiepark is professional translator who is very well-known in South Korea :)
I reckon we can close this PR now and merge into master

**Review by kimdanny — COMMENTED** [review]
Perfect translation!

**Comment by shervinea** [comment]
Thanks @kimdanny for your review, and thanks again @rickiepark for your work great work!

**Pull request merged**
