### PR TITLE
[tr] Recurrent neural networks

### PR DESCRIPTION
**Pull request by basakbuluz**
I translated the CS 230 (Deep Learning) - Recurrent neural networks to Turkish. @shervinea can you please review it?

### CODE REVIEW

**Comment by shervinea** [comment]
Awesome, thanks for your work @basakbuluz! Now, let's wait for other native speakers to come and review the content.

**Comment by basakbuluz** [comment]
@yavuzKomecoglu, Thanks for the detailed review.
@shervinea, editing of all suggestions is complete.

**Comment by shervinea** [comment]
Thanks again to the both of you!

**Comment by tolgacesur** [comment]
@basakbuluz @yavuzKomecoglu Thanks guys!

**Pull request merged**
