### PR TITLE
[ko] Unsupervised Learning

### PR DESCRIPTION
**Pull request by kwanghyeokahn**
i`m progressing =]

### CODE REVIEW

**Comment by kwanghyeokahn** [comment]
Hello 
I finish translation of Unsupervised Learning =] 
but i have a question 
No.51 The Machine Learning cheatsheets are now available in Japanese.
this cheatsheets for Korean so i think Japanese should change Korean.

**Comment by shervinea** [comment]
Thanks for your work @kwanghyeokahn! 

You are right -- the template should indicate Koran instead.

**Comment by kwanghyeokahn** [comment]
Thx for answer it  =] 

Have a good day ~

**Comment by shervinea** [comment]
Great job @kwanghyeokahn and thank you for your prompt response! 

Now, we can get started with the review process (cc: @WooilJeong).

**Comment by sy95lee** [comment]
It's perfect!

**Comment by WooilJeong** [comment]
good translation!

**Pull request merged**
