### PR TITLE
[fa] Probabilities and Statistics

### PR DESCRIPTION
**Pull request by erfannoury**
Persian translation of the Probabilities and Statistics refresher document.

cc: @m-karimi

### CODE REVIEW

**Comment by shervinea** [comment]
Truly awesome work @erfannoury and @m-karimi. I had two questions in mind:
1. There were a few questions added to the list (cf. questions 59-64 of [this updated template](https://github.com/shervinea/cheatsheet-translation/blob/master/es/refresher-probability.md)), could you please take a look at them as well?
2. It seems that Markdown is not optimized for languages that are written from right to left, as I sometimes see words being displayed in the wrong order. Would you know how to deal with this issue?

**Comment by shervinea** [comment]
1. Thank you for being so fast!
2. No, the Markdown files are just a means for conveying the translated terms. Would you know of a file format that doesn't suffer from inconsistencies in right-to-left settings?

**Comment by erfannoury** [comment]
I don't think any particular file format would correctly handle RTL cases. Only the system that displays those files can handle this case. I have seen some Markdown files (like [this](https://github.com/sobhe/moratab/blob/master/README.md)) handle this by adding `<div dir="rtl">` to the beginning of the file. 
If we add it to the beginning of the file even the English lines will be displayed RTL, but if we add the opening tag before every Persian translation and close the tag afterwards, it can correctly display them in Github.

**Comment by shervinea** [comment]
Great trick!

**Comment by shervinea** [comment]
Thank you @erfannoury for everything. Awesome job again! Will proceed with all the merges.

**Pull request merged**
